version: "3.8"
services:
  db:
    image: postgres
    container_name: mopcommercePG
    restart: always
    ports:
      - "3001:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mopcommerce
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: mopcommercePGADMIN
    restart: always
    ports:
      - "3002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: valeri_petkov01@abv.bg
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: